---
title: "DO_magnitude"
author: "Ming Chen"
date: "2023-11-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
if (!require("pacman"))
   install.packages("pacman")
pacman::p_load(tidyverse, skimr)

# Load necessary libraries
library(ggplot2)
library(lubridate)
```

```{r}
setwd("C:/Users/chenm/Desktop/Kevin_senior_thesis/DO_magnitude")
data <- read.csv("Daily_DO_Temp_Magnitudes.csv")
data$Season <- factor(data$Season, levels = c("Spring", "Summer", "Fall", "Winter"))
```

```{r}
# time series plot for DO_magnitude
DO_magnitude_series <- ggplot(data, aes(x=Month, y=DO_Magnitude, color=Season)) +
  geom_point() +
  labs(title="Time Series for DO magnitude",
       x="Month",
       y="DO amplitude (mg L-1)") +
  scale_color_manual(values=c("Winter"="#4DADCF", "Summer"= "coral1","Fall"="#E9943A", "Spring"="#5EC795")) +
  theme_minimal()
DO_magnitude_series
```

```{r}
# time series plot for DO_Minimum
DO_Minimum_series <- ggplot(data, aes(x=Month, y=Min_DO)) +
  geom_point() +
  labs(title="Time Series for Minimum DO",
       x="Month",
       y="Minimum DO (mg L-1)") +
  theme_minimal()
DO_Minimum_series
```

```{r}
# box plot for DO magnitude
DO_magnitude_box <- ggplot(data, aes(x = Season, y = DO_Magnitude)) + 
  geom_boxplot() + 
  labs(title = "Box Plot of DO Amplitude by Season", x = "Season", y = "DO Amplitude (mg L-1)") +
  geom_dotplot(binaxis='y', stackdir='center', binwidth=0.1) +
  theme_minimal() +
  theme(plot.title = element_text(size = 20), # Adjust the size of the plot title
        axis.title.x = element_text(size = 16), # Adjust the size of the x-axis title
        axis.title.y = element_text(size = 16), # Adjust the size of the y-axis title
        axis.text.x = element_text(size = 14), # Adjust the size of the x-axis text
        axis.text.y = element_text(size = 14)) # Adjust the size of the y-axis text
DO_magnitude_box
ggsave("DO_magnitude_box.png", width = 750*4, height = 600*4, units = "px")
```

```{r}
dataLong <- data %>%
  gather(Max_DO, Min_DO, key = "Parameter", value = "Value")

# box plot for DO Minimum
DO_extremes_box <- ggplot(dataLong, aes(x = Season, y = Value, fill = Parameter)) + 
  geom_boxplot() + 
  labs(title = "Box Plot of Maxiumum and Minimum DO by Season", x = "Season", y = "DO (mg L-1)") +
  geom_dotplot(binaxis='y', stackdir='center', position=position_dodge(0.7), binwidth=0.1) +
  scale_fill_manual(values=c("Max_DO"="coral1", "Min_DO"="#4DADCF")) +
  theme_minimal() +
  theme(plot.title = element_text(size = 20), # Adjust the size of the plot title
        axis.title.x = element_text(size = 16), # Adjust the size of the x-axis title
        axis.title.y = element_text(size = 16), # Adjust the size of the y-axis title
        axis.text.x = element_text(size = 14), # Adjust the size of the x-axis text
        axis.text.y = element_text(size = 14)) # Adjust the size of the y-axis text
DO_extremes_box
ggsave("DO_extremes_box.png", width = 750*4, height = 600*4, units = "px")
```

