---
title: "EFC_analysis"
author: "Ming Chen"
date: "2023-08-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
if (!require("pacman"))
   install.packages("pacman")
pacman::p_load(tidyverse, skimr)
library(scales)
```

# import the csv file that summarizes baseMetab results
```{r}

library(readxl)
Data <- read_excel("compiled_metab.xlsx")
Data <- Data %>% mutate(DayMonth = format(Date, "%m/%d"))
Data$Season <- factor(Data$Season, levels = c("Spring", "Summer", "Fall", "Winter"))
Data$type <- ifelse(Data$Date < as.Date("2023-07-01"), "original", "complementary")

```

# Convert all MonthDay variable into DateTime variable and set the year to 2022
```{r}

Data$full_dates <- as.POSIXct(paste( Data$DayMonth, "2024", sep = "/"), format = "%m/%d/%y")
```

# Skim the data based on the seasons
```{r}
list(
  Spring = skim(filter(Data, Season == "Spring")),
  Summer = skim(filter(Data, Season == "Summer")),
  Autumn = skim(filter(Data, Season == "Fall")),
  Winter = skim(filter(Data, Season == "Winter"))
)
```


# plot GPP vs ER
```{r}
p <- ggplot(Data, aes(x = GPP.mean, y = ER.mean, color = Season)) +
  geom_point(size = 2) +
  geom_abline() +
  labs(title="GPP and ER in EFC, May 2022 - December 2023",
       x="GPP (mg O2 L-1 d-1)",
       y="ER (mg O2 L-1 d-1)") +  
  scale_x_continuous(breaks = seq(0, 90, 30), 
                     limits=c(0, 100)) + 
  #scale_y_continuous(breaks=seq(0,30,by=15)) +
  scale_color_manual(values=c("Winter"="#4DADCF", "Summer"= "coral1","Fall"="#E9943A", "Spring"="#5EC795")) +
  theme_bw()
ggsave("heterotrophic.png", width = 600*3, height = 500*3, units = "px")
print(p)
```

```{r}
DataLong <- Data %>%
  rename(GPP = GPP.mean, ER = ER.mean, NEP = NEP.mean) %>%
  gather(GPP, ER, NEP, key = "Parameter", value = "Value")
  
DataLong$max <- c(0)
DataLong$min <- c(0)
j <- nrow(DataLong)
for (i in 1:j) {
  if (DataLong$Parameter[i] == "GPP") {
  DataLong$max[i] <- DataLong$Value[i] + DataLong$GPP.sd[i]
  DataLong$min[i] <- DataLong$Value[i] - DataLong$GPP.sd[i]
}  
else if (DataLong$Parameter[i] == "ER") {
  DataLong$max[i] <- DataLong$Value[i] + DataLong$ER.sd[i]
  DataLong$min[i] <- DataLong$Value[i] - DataLong$ER.sd[i]
} 
  else {
  DataLong$max[i] <- DataLong$Value[i] + DataLong$NEP.sd[i]
  DataLong$min[i] <- DataLong$Value[i] - DataLong$NEP.sd[i]
}
}
DataLong$Parameter <- factor(DataLong$Parameter)
DataPlot <- DataLong %>%
  select(Date, Parameter, Value, max, min)
```

# individual time series for GPP, ER, NEP
```{r}
p <- ggplot(DataLong%>%filter(Date < "2023-8-1"), aes(x = Date, y = Value)) +
  geom_point(size = 2) +
  geom_smooth(method = "loess", fill='darkred', 
              level=0.90) +
  labs(title = "Stream Metabolism Summary, May 2022 - May 2023",
       x="Month",
       y="Value (mg O2 L-1 d-1)") +
  theme_bw()+
  facet_wrap(~Parameter, scales = "free", ncol = 1)
ggsave("metab_summary.png", width = 750*4, height = 600*4, units = "px")
print(p)
```

# Combine same month in different years
```{r}
p <- ggplot(DataLong, aes(x = full_dates, y = Value)) +
  geom_point(aes(color = type),size = 2) + 
  scale_color_manual(values=c("original"="black", "complementary"= "#4DADCF")) +
  geom_smooth(method = "loess", fill='darkgray', 
              level=0.90) +
  scale_x_datetime(labels = date_format("%b")) + # Format x-axis labels
  labs(title = "Stream Metabolism Summary, all measurements",
       x="Month",
       y="Value (mg O2 L-1 d-1)") +
  theme_bw()+ 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_wrap(~Parameter, scales = "free", ncol = 1)
ggsave("metab_summary_all.png", width = 750*4, height = 600*4, units = "px")
print(p)
```

```{r}
p <- ggplot(DataLong, aes(x = full_dates, y = Value)) +
  geom_point(aes(color = type), size = 2) + 
  scale_color_manual(values = c("original" = "black", "complementary" = "#4DADCF")) +
  geom_smooth(method = "loess", fill = 'darkgray', level = 0.90) +
  scale_x_datetime(date_breaks = "1 month", date_labels = "%b") + # Adjusted line
  labs(title = "Stream Metabolism Summary, all measurements",
       x = "Month",
       y = "Value (mg O2 L-1 d-1)") +
  theme_bw() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_wrap(~Parameter, scales = "free", ncol = 1)

ggsave("metab_summary_all.png", p, width = 750*4, height = 600*4, units = "px")
print(p)
```


# plot out k vs NEP
```{r}
p <- ggplot(Data, aes(x = K.mean, y = NEP.mean, color = Season)) +
  geom_point() +
  scale_color_manual(values=c("Winter"="#4DADCF", "Summer"= "coral1","Fall"="#E9943A", "Spring"="#5EC795")) +
  geom_segment(aes(x = 10, y = -Inf, xend = 10, yend = -10), linetype = "dashed", color = "red") +  # Vertical segment
  geom_segment(aes(x = -Inf, y = -10, xend = 10, yend = -10), linetype = "dashed", color = "red") +  # Horizontal segment
  scale_x_continuous(breaks = seq(0, 90, 30), 
                     limits=c(0, 100)) + 
  labs(x="K (d-1)",
       y="NEP (mg O2 L-1 d-1)") +
  theme_bw()

ggsave("K_NEP.png", width = 550*3, height = 496*3, units = "px")
print(p)
```

