---
title: "instantaneous_diurnal_202207"
author: "Ming Chen"
date: "2023-11-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(tidyverse, skimr)
```

```{r}
library(ggplot2)
library(lubridate)
library(corrplot)
```

```{r}
setwd("C:/Users/chenm/Desktop/Kevin_senior_thesis/Diurnal_variation")
library(readxl)
Data <- read_excel("2022_07_instantaneous_rates_EXO.xlsx")
Data <- rename(Data,
  'Temperature_C' = tempC,
  'K_d-1' = K,
  'GPP_mgO2L-1d-1' = GPP,
  'ER_mgO2L-1d-1' = ER,
  'NEP_mgO2L-1d-1' = NEP)
skim(Data)
```


# test the established scaling law 
Abdul-Aziz, O. I., & Gebreslase, A. K. (2023). Emergent Scaling of Dissolved Oxygen (DO) in Freshwater Streams Across Contiguous USA. Water Resources Research, 59(2). https://doi.org/10.1029/2022WR032114
```{r}
Data$temp = Data$Temperature_C + 273.15
Data$model_DO = 10^18.94 * Data$temp^-7.46 * Data$pH^0.45

# Remove unequilibrate data
df <- Data %>% filter(ODO_mg_L > 5.5)

# Fit a linear model
model <- lm(model_DO ~ ODO_mg_L, df)

# Extract coefficients and calculate R^2
intercept <- round(coef(model)[1], 2)
slope <- round(coef(model)[2], 2)
r_squared <- round(summary(model)$r.squared, 2)

# Create the regression equation string
equation <- paste("y =", intercept, "+", slope, "x, R^2 =", r_squared)

p <- ggplot(df, aes(x = ODO_mg_L, y = model_DO)) +
  geom_point()+
  geom_smooth(method = "lm", formula = y ~ x, se = FALSE, color = "blue") +  # Add linear regression line
  labs(x = "Measured DO (mg L-1)",
       y = "Predicted DO (mg L-1)") +
  annotate("text", x = 10, y = 6.9, label = equation, hjust = 1, vjust = 1, size = 4, color = "black") +  
  theme_bw()
ggsave("DO_scaling.png", width = 425*3, height = 496*3, units = "px")
print(p)
```

```{r}
# Fit a linear model
model2 <- lm(ODO_mg_L ~ Temperature_C, data = df)

# Extract coefficients and calculate R^2
intercept <- round(coef(model2)[1], 2)
slope <- round(coef(model2)[2], 2)
r_squared <- round(summary(model2)$r.squared, 2)

# Create the regression equation string
equation <- paste("y =", intercept, "+", slope, "x, R^2 =", r_squared)

p <- ggplot(df, aes(x = Temperature_C, y = ODO_mg_L)) +
  geom_point()+
  geom_smooth(method = "lm", formula = y ~ x, se = FALSE, color = "blue") +  # Add linear regression line
  labs(x = "Temperature (\u00B0C)",
       y = "Measured DO (mg L-1)") +
  annotate("text", x = 26, y = 11.5, label = equation, hjust = 1, vjust = 1, size = 4, color = "black") +  
  theme_bw()
ggsave("DO_tempC.png", width = 425*3, height = 496*3, units = "px")
print(p)
```

```{r}
# time series for selected parameters
DataFacet <- transmute(Data, DateTime, I, Light_lux, `K_d-1`, `GPP_mgO2L-1d-1`, 
                       `ER_mgO2L-1d-1`, `NEP_mgO2L-1d-1`, Temperature_C, pH,
                        ODO_per_local)
DataFacetLong <- pivot_longer(DataFacet, names_to = "variable",
                              values_to = "measurement", `K_d-1`:ODO_per_local)
DataFacetLong$variable <- factor(DataFacetLong$variable, 
                               levels = c("Temperature_C","K_d-1", "GPP_mgO2L-1d-1",
                                          "ER_mgO2L-1d-1", "NEP_mgO2L-1d-1", "pH", 
                                          "ODO_per_local"))

p <- ggplot(DataFacetLong, aes(x=DateTime)) +
  theme_linedraw() +
  # Here try preferred method of continuous shading based on light intensity 
  geom_segment(aes(x = DateTime, xend = DateTime, y = -Inf, yend = Inf, color = log(I))) +
  scale_color_gradient(low = "grey", high = "white", name = "Log(PAR)") +
  ylab("Value") + 
  geom_line(aes(y = measurement), color = "#4DADCF") +
  facet_wrap(~ variable, scales = "free", nrow = 2)
ggsave("diurnal_instantaneous_selected.jpg", width = 750*4, height = 600*4, units = "px")
print(p)
```



```{r}
DataFacet <- transmute(Data, DateTime, I, Light_lux, `K_d-1`, `GPP_mgO2L-1d-1`, 
                       `ER_mgO2L-1d-1`, `NEP_mgO2L-1d-1`, Temperature_C, pH, Depth_m,
                       SpCond_μS_cm, ODO_per_local, fDOM_RFU, Chlorophyll_RFU, TAL_PC_RFU)
DataFacetLong <- pivot_longer(DataFacet, names_to = "variable",
                              values_to = "measurement", `K_d-1`:TAL_PC_RFU)
DataFacetLong$variable <- factor(DataFacetLong$variable, 
                               levels = c("Temperature_C","K_d-1", "GPP_mgO2L-1d-1",
                                          "ER_mgO2L-1d-1", "NEP_mgO2L-1d-1", "pH", 
                                          "Depth_m", "SpCond_μS_cm", 
                                          "ODO_per_local", "fDOM_RFU", 
                                          "Chlorophyll_RFU", "TAL_PC_RFU"))

p <- ggplot(DataFacetLong, aes(x=DateTime)) +
  theme_linedraw() +
  # Here try preferred method of continuous shading based on light intensity 
  geom_segment(aes(x = DateTime, xend = DateTime, y = -Inf, yend = Inf, color = log(I))) +
  scale_color_gradient(low = "grey", high = "white", name = "Log(PAR)") +
  ylab("Value") + 
  geom_line(aes(y = measurement), color = "#4DADCF") +
  facet_wrap(~ variable, scales = "free", nrow = 3)
ggsave("diurnal_instantaneous.jpg", width = 750*4, height = 600*4, units = "px")
print(p)
```

```{r}
# plot DO and equilibrium DO (at saturation)
Data$ODO_eq_mg_L = Data$ODO_mg_L / Data$ODO_per_local * 100
p <- ggplot(Data, aes(x = DateTime)) +
  geom_tile(data = Data, aes(x = DateTime, y = 0, fill = log(I)), height = Inf) +
  scale_fill_gradient(low = "darkgrey", high = "white", name = "log(PAR)") + # Adjust colors as needed
  geom_line(aes(y = ODO_mg_L, color = "Measured DO"), linewidth = 0.8) +
  geom_line(aes(y = ODO_eq_mg_L, color = "Equilibrium DO"), linewidth = 0.8) +
  labs(title = "Time Series Plot of Measured and Equilirium DO",
       x = "DateTime",
       y = "Values (mg/L)",
       color = "Legend",
       fill = "Log(PAR)") +
  scale_color_manual(values = c("Measured DO" = "#4DADCF", "Equilibrium DO" = "coral1")) +
  theme_minimal() +
  theme(plot.title = element_text(size = 20), # Adjust the size of the plot title
        axis.title.x = element_text(size = 16), # Adjust the size of the x-axis title
        axis.title.y = element_text(size = 16), # Adjust the size of the y-axis title
        axis.text.x = element_text(size = 16), # Adjust the size of the x-axis text
        axis.text.y = element_text(size = 16)) # Adjust the size of the y-axis text

ggsave("measure_vs_equ.jpg", width = 750*4, height = 600*4, units = "px")
print(p)
```


```{r}
DataFacet <- transmute(Data, DateTime, Light_lux, `K_d-1`, `GPP_mgO2L-1d-1`, 
                       `ER_mgO2L-1d-1`, `NEP_mgO2L-1d-1`, Temperature_C, pH, Depth_m,
                       SpCond_μS_cm, ODO_per_local, fDOM_RFU, Chlorophyll_RFU, TAL_PC_RFU)
DataFacetLong <- pivot_longer(DataFacet, names_to = "variable",
                              values_to = "measurement", `K_d-1`:TAL_PC_RFU)
DataFacetLong$variable <- factor(DataFacetLong$variable, 
                               levels = c("Temperature_C","K_d-1", "GPP_mgO2L-1d-1",
                                          "ER_mgO2L-1d-1", "NEP_mgO2L-1d-1", "pH", 
                                          "Depth_m", "SpCond_μS_cm", 
                                          "ODO_per_local", "fDOM_RFU", 
                                          "Chlorophyll_RFU", "TAL_PC_RFU"))

p <- ggplot(DataFacetLong, aes(x=DateTime)) +
  theme_linedraw() +
  # Here try preferred method of continuous shading based on light intensity 
  geom_tile(data = DataFacetLong, aes(x = DateTime, y = 0, fill = log(Light_lux)), height = Inf) +
  scale_fill_gradient(low = "darkgrey", high = "white") + # Adjust colors as needed
  ylab("Value") +
  geom_line(aes(y = measurement), color = "#4DADCF") +
  facet_wrap(~ variable, scales = "free", nrow = 3)

ggsave("diurnal_instantaneous_with_shade.png", width = 750*4, height = 600*4, units = "px")
print(p)
```


```{r}
# Correlation Matrix
Parameters <- select(DataFacet, -c(DateTime))
Corr <- cor(Parameters, use = "pairwise.complete.obs", method = "spearman")
testRes = cor.mtest(Parameters, conf.level = 0.95)
#corrplot(Corr, method="circle", type = 'lower', order = "hclust", addCoef.col = 'black',
         #p.mat = testRes$p, insig='blank', tl.col = 'black', tl.cex = 2,
         #cl.ratio = 0.3,tl.srt = 45, diag=FALSE)

# print the plot
png("instantaneous_correlation.png", width = 600*2, height = 600*2)
corrplot(Corr, method="circle", type = 'lower', order = "hclust", addCoef.col = 'black',
         p.mat = testRes$p, insig='blank', tl.col = 'black', tl.cex = 2,
         cl.cex = 2, cl.ratio = 0.15,tl.srt = 45, diag=FALSE)
dev.off()
```


